train:
  model: "sovits"
  seed: 1234
  epochs: 10000
  learning_rate_g: 1e-4
  learning_rate_d: 1e-4
  betas: [0.8, 0.99]
  lr_decay: 0.99
  eps: 1e-9
  batch_size: 4
  accum_iter: 4
  freeze_step: 1
  disc_iter: 1
  c_score: 1.
  c_feat: 2.
  c_dis: 1.
  c_stft: 9.
  c_mel: 5.
  c_kl: 0.2
  c_spk: 0.0
  c_cont: 1.0
  port: 8001
  pretrain: /home/mluser/so-vits-5/ckpt/karanovc_min_lr_1e4_sraug/karanovc_min_lr_1e4_sraug_0012.pt
  pretrain_disc: false #/home/mluser/so-vits-5/bigvgan_base_22khz_80band/do_05000000.zip
  freeze_module: false # ["emb_g", "emb_p", "enc_q", "flow"]
#############################
data: 
  training_files: "files/train_big_with_song.txt"
  validation_files: "files/valid_big_with_song.txt"
  segment_size: 8192 # 6400  # WARNING: base on hop_length
  max_wav_value: 32768.0
  sampling_rate: 22050
  filter_length: 1024
  hop_length: 256
  win_length: 1024 # 1024
  mel_channels: 80 # 100
  mel_fmin: 0 # 50.0
  mel_fmax: 11025 # 11025 #16000.0
#############################
vits:
  ppg_dim: 0
  vec_dim: 768
  spk_dim: 512
  gin_channels: 256
  inter_channels: 192
  hidden_channels: 192
  filter_channels: 768
#############################
gen:
  upsample_input: 192
  upsample_rates: [4,4,2,2,2,2] # [8, 8, 2, 2] # [5,4,4,2,2] # [4,4,2,2,2,2]
  upsample_kernel_sizes: [8,8,4,4,4,4] # [16, 16, 4, 4] #[15,8,8,4,4] #[8,8,4,4,4,4]
  upsample_initial_channel: 1536 # 1536 512
  resblock_kernel_sizes: [3,7,11]
  resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
#############################
mpd:
  periods: [2,3,5,7,11]
  kernel_size: 5
  stride: 3
  use_spectral_norm: False
  lReLU_slope: 0.1
#############################
mrd:
  resolutions: "[(1024, 120, 600), (2048, 240, 1200), (512, 50, 240)]" #(4096, 480, 2400), (512, 50, 240)]" # (filter_length, hop_length, win_length) 1024 320 1024
  use_spectral_norm: False
  lReLU_slope: 0.1
#############################
log:
  info_interval: 100
  eval_interval: 1
  save_interval: 1
  num_audio: 6
  pth_dir: 'ckpt'
  log_dir: 'logs'
  keep_ckpts: 2
#############################
dist_config:
  dist_backend: "nccl"
  dist_url: "tcp://localhost:54321"
  world_size: 1

